# All of these are instructions to docker to build a container
# Containers are layered
FROM node:12-stretch

# Will always take the last one; if there are two CMDs, the latest instruction is run
CMD ["node", "-e", "console.log('Hi lolu')"]